name: Python application

on:
  schedule:
    - cron: '0 0 * * *'  # 每天UTC时间午夜运行
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install arxiv pdf2image  # 安装额外的依赖
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run daily_arxiv.py script  # 运行您的脚本
      run: |
        python daily_arxiv.py
